"""change database

Revision ID: 6b4d0802dd4f
Revises: 
Create Date: 2025-07-29 16:58:36.231326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b4d0802dd4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем новые столбцы
    op.add_column('arbitration_manager_contacts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('arbitration_manager_contacts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('arbitration_managers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('arbitration_managers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('direct_trades', sa.Column('message_number', sa.String(length=10), nullable=True))
    op.add_column('direct_trades', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('direct_trades', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('direct_trades', 'debtor_inn',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('lots', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('lots', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sros', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sros', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_actions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_actions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Откатываем изменения в обратном порядке
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('user_actions', 'updated_at')
    op.drop_column('user_actions', 'created_at')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('sros', 'updated_at')
    op.drop_column('sros', 'created_at')
    op.drop_column('lots', 'updated_at')
    op.drop_column('lots', 'created_at')
    op.alter_column('direct_trades', 'debtor_inn',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    op.drop_column('direct_trades', 'updated_at')
    op.drop_column('direct_trades', 'created_at')
    op.drop_column('direct_trades', 'message_number')
    op.drop_column('arbitration_managers', 'updated_at')
    op.drop_column('arbitration_managers', 'created_at')
    op.drop_column('arbitration_manager_contacts', 'updated_at')
    op.drop_column('arbitration_manager_contacts', 'created_at')
    
    # Восстанавливаем только таблицу client_crud_tag
    op.create_table('client_crud_tag',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###